name: Update DSA Progress Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Badge Update Script
        run: node scripts/updateBadge.js

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Praveen Yadav'
          git config --global user.email 'ypraveen@gmail.com'
          git add README.md
          git commit -m "update: progress badge" || echo "No changes"
          git push
